# Generated by Django 5.2.3 on 2025-06-24 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='autor',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='cuerpo',
            new_name='body',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='creado',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='estado',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='titulo',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='actualizado',
            new_name='updated',
        ),
    ]
